version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  kwetter.kweetservice:
    image: ${DOCKER_REGISTRY-}kwetterkweetservice
    build:
      context: .
      dockerfile: Kwetter.KweetService/Dockerfile


  kwetter.likeservice:
    image: ${DOCKER_REGISTRY-}kwetterlikeservice
    build:
      context: .
      dockerfile: Kwetter.LikeService/Dockerfile


  kwetter.userservice:
    image: ${DOCKER_REGISTRY-}kwetteruserservice
    build:
      context: .
      dockerfile: Kwetter.UserService/Dockerfile

