---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kweetservice
    spec:
      containers:
      - name: kweetservice
        image: mustafa2x/kweetservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: kweetservice
---
apiVersion: v1
kind: Service
metadata:
  name: kweetservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kweetservice
