apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-kweetservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwetter-kweetservice
  template:
    metadata:
      labels:
        app: kwetter-kweetservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: kwetter-kweetservice
        image: mustafa2x/kweetservice:latest
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: redis
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: kwetter-kweetservice-srv
spec:
  type: ClusterIP
  selector:
    app: kwetter-kweetservice
  ports:
  - name: kwetter-kweetservice
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kwetter-np-kweetservice-srv
spec:
  type: NodePort
  selector:
    app:  kwetter-kweetservice
  ports:
    - name:  kwetter-kweetservice
      protocol: TCP
      port: 80
      targetPort: 80