name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debugging Info
      run: |
        echo "Current directory: $PWD"
        ls -la
        echo "Contents of service-account.json:"
        cat service-account.json

    - name: Set up Service Account
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "$GCP_SA_KEY" > service-account.json
        gcloud auth activate-service-account --key-file=service-account.json
        gcloud config set project quad-test-401209

    - name: Deploy to GCE
      run: |
        echo "Pulling Docker image and running..."
        gcloud compute ssh quad-test --zone=europe-west3-c --command="docker pull gcr.io/quad-test-401209/docker-compose-container && docker run -v /var/run/docker.sock:/var/run/docker.sock gcr.io/quad-test-401209/docker-compose-container up -d"
