name: Docker Build and Deploy

on:
  push:
    branches:
      - main # Adjust this if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: List the content of the current directory
    - name: List directory contents
      run: ls -al

    # Step 3: Disable BuildKit
    - name: Disable BuildKit
      run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

    # Step 4: Build the Docker image with explicit context
    - name: Build Docker Image
      run: docker build -f ./Dockerfile -t your-image-name .

    # Additional steps for your workflow (like pushing the image) can go here...
