name: Build KweetService 

on:
  push:
    paths:
      - "Kwetter.KweetService/**"
      - ".github/workflows/KweetService.yml"

env:
  PROJECT_PATH: 'Kwetter.KweetService/Kwetter.KweetService.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: KweetService_Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kweetservice:latest
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.AZ_SP_CLIENT_ID }}
        password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

    - name: Build Docker image
      run: docker build

    - name: Push Docker image to Azure Container Registry
      run: |
          docker tag kweetservice ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/kweetservice:${{ github.sha }}
          docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/kweetservice:${{ github.sha }}            
