name: Push Image to ACR 

on:
  push:
    paths:
      - "Kwetter.KweetService/**"
      - ".github/workflows/KweetServiceACR.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: dotnet
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: kwettercontainerregistery.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t kwettercontainerregistery.azurecr.io/kweetservice:${{ github.sha }}
        docker push kwettercontainerregistery.azurecr.io/kweetservice:${{ github.sha }}
