name: Build KweetService 

on:
  push:
    paths:
      - "Kwetter.KweetService/**"
      - ".github/workflows/KweetService.yml"

env:
  PROJECT_PATH: 'Kwetter.KweetService/Kwetter.KweetService.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: KweetService_Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kweetservice:latest
        
    - name: Build Container Image
      uses: actions/checkout@v2
      
    - name: Login ACR and Push
    - uses: azure/docker-login@v1
      with:
        login-server: kwettercontainerregistery.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t kwettercontainerregistery.azurecr.io/myapp:${{ github.sha }}
        docker push kwettercontainerregistery.azurecr.io/myapp:${{ github.sha }}
