name: Build KweetService 

on:
  push:
    paths:
      - "Kwetter.KweetService/**"
      - ".github/workflows/KweetService.yml"

env:
  PROJECT_PATH: 'Kwetter.KweetService/Kwetter.KweetService.csproj'
  IMAGE_NAME: kweetservice

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-build --verbosity normal
    
    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: KweetService_Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/kweetservice:latest
        
        
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Log into registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.ACR_ENDPOINT }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          version=${{ steps.tag.outputs.tag }}
          tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}
